# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-14 18:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_label', models.CharField(max_length=100)),
                ('issue_comment', models.CharField(max_length=20000)),
                ('issue_category', models.CharField(max_length=30)),
                ('issue_assignee', models.CharField(max_length=50)),
                ('issue_status', models.CharField(max_length=30)),
                ('issue_dump', models.TextField()),
                ('pub_date', models.DateTimeField(verbose_name='Date reported')),
                ('close_date', models.DateTimeField(verbose_name='Date closed')),
            ],
        ),
        migrations.AddField(
            model_name='assignee',
            name='issues',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issues.Issue'),
        ),
    ]
